### ISSUE TITLE
Agenda 15 August

### ISSUE THREAD

**Issue by arojascastro** [hdcaicyt/Recogito-TEI#15]
Please fill in with more tasks or topics:

## Review of TEI encoding
- [ ] xml:id used in relation: https://github.com/hdcaicyt/Recogito-TEI/issues/8
- [ ] listPlace and listPerson: https://github.com/hdcaicyt/Recogito-TEI/issues/10
- [ ] @:ana isn't a pointer: https://github.com/hdcaicyt/Recogito-TEI/issues/13
- [ ] < p > elements in < body >: https://github.com/hdcaicyt/Recogito-TEI/issues/16
- [ ] import and export TEI files: https://github.com/hdcaicyt/Recogito-TEI/issues/18
- [ ] something else?

## Integration with publishing solutions 
-  [ ] Set up export for Ed/Markdown: https://github.com/hdcaicyt/Recogito-TEI/issues/14
-  [ ] What do we need to know about CETEIcean and how can we contribute? 

## Outreach
-  [ ] Proposal for Writing Sprint tutorial SP-EN 
-  [ ]  Workshop in Buenos Aires? 

## Pelagios Network
- Latest news

**Comment by arojascastro** [comment]
We agreed to expand the issues that suggest a change and give more details and examples so it is easier for @rsimon to understand our views. We will use the Wiki to document in a more or less stable manner our proposal. 

We also agreed that we should focus on the integration with ED and CETEIcean in our next meeting in September.
