### ISSUE TITLE
Agenda Fourth Recogito-TEI meeting (11/09/2019)

### ISSUE THREAD

**Issue by arojascastro** [hdcaicyt/Recogito-TEI#20]
Add tickets and topics if necessary.

### Integration 
- [x] xml:id used in relation: https://github.com/hdcaicyt/Recogito-TEI/issues/8
- [ ] listPlace and listPerson: https://github.com/hdcaicyt/Recogito-TEI/issues/10
- [x] @ana isn't a pointer: https://github.com/hdcaicyt/Recogito-TEI/issues/13
- [ ] Proper display of TEI header in GUI?: https://github.com/hdcaicyt/Recogito-TEI/issues/19

### publishing minimal editions
- [ ] Jekyll: https://github.com/hdcaicyt/Recogito-TEI/issues/14
- [ ] creation of an issue about ceteian is pending
